config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, except: [:edit, :update]
  resources :movies, only: [:index, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  has_many_attached :photos
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # add a new bookmark (movie/list pair) to an existing list
  def new
    # get details of movie/list pair from users
    @movie = Movie.find(params[:movie_id])
    @bookmark = Bookmark.new
  end

  def create
  # POST movie/list pair to exist list
    @movie = Movie.find(params[:movie_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.movie = @movie
    @bookmark.save
    redirect_to list_path(@bookmark.list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path(@list)
  end


  private

  def list_params
    params.require(:list).permit(:name, photos: [])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster_url, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h2>Add bookmark for movie: <%= @movie.title  %></h2>
  <%= simple_form_for([@movie, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :list%>
  <%= f.submit %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @article.photo.key, height: 300, crop: :fill %>')"
>
  Cool article
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<h1>Add new list to List</h1>
<%= simple_form_for(list) do |f|%>
  <%= f.input :name %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="container">
  <h1>Lists(movies) to watch</h1>

  <ul>
    <% @lists.each do |i| %>
      <li>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <%= i.name %>
        <%= link_to i.name, list_path(i) %>
        </div>
      </li>
    <% end %>
  </ul>
  <p><%= link_to "add new list", new_list_path, class: "btn btn-primary"  %></p>
</div>

<%# <div class="cards">

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    Lunch
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    Dinner
  </div>
</div> %>

app/views/lists/new.html.erb
<div class="container">
  <p><%= render "form", list: @list %></p>
  <p><%= link_to "view all lists", lists_path(@list), class: "btn btn-primary"  %></p>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
  <h2>show list of movies <%= @list.name %></h2>
  <% @list.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>
  <ul>
    <% @list.bookmarks.each do |bookmark| %>
      <li><%= bookmark.comment %></li>
      <li><%= bookmark.movie.title %></li>
    <% end %>
      TODO: LINK TO MOVIE SHOW PAGE / DELETE MOVIE FROM LIST/ADD MOVIE TO LIST/GET BACK TO LISTS
  </ul>
</div>

app/views/movies/index.html.erb
<div class="container">
  <h1>all movies</h1>
  <ul>
    <% @movies.each do |movie| %>
      <li>
        <%= movie.title %>
        <%= link_to movie.title, movie_path(movie) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h1><%= @movie.title %></h1>
  <ul>
      <li>Overview:<%= @movie.overview %></li>
      <li>link:<%= @movie.poster_url %></li>
      <li>Rating<%= @movie.rating %>/5</li>
      <%= link_to "back to list", movies_path(@movie) %>
      <%= link_to "add book mark to this movie", new_movie_bookmark_path(@movie) %>
      </li>
  </ul>
</div>